name: Publish Docker Images

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.frontend
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
          push: true

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.backend
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest
          push: true

      - name: Build and push nginx
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nginx:latest
          push: true


# name: Tests 14 sprint

# on:
#   push:
#     branches:
#       - '**'
#     tags:
#       - '**'
# env:
#   DIR_TESTS: /tmp/tests-back-to-the-film
#   REP_TESTS: https://github.com/Yandex-Practicum/tests-back-to-the-film.git
# jobs:
#   test_backend:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Set up GitHub Actions
#       uses: actions/checkout@v4
#     - name: Use Node.js 18.x
#       uses: actions/setup-node@v4
#       with:
#         node-version: 18.x
#     - name: Get testing lib
#       run: set -eu && git clone --depth 1 $REP_TESTS $DIR_TESTS
#     - name: Run tests
#       run: bash $DIR_TESTS/bin/backend.sh
#   test_endpoints:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Set up GitHub Actions
#       uses: actions/checkout@v4
#     - name: Use Node.js 18.x
#       uses: actions/setup-node@v4
#       with:
#         node-version: 18.x
#     - name: Get testing lib
#       run: set -eu && git clone --depth 1 $REP_TESTS $DIR_TESTS
#     - name: Start project
#       run: bash $DIR_TESTS/bin/start_project.sh
#     - name: Run tests
#       run: bash $DIR_TESTS/bin/endpoints.sh
